jQuery(document).ready(function(){
jQuery("#server-items").hide();
jQuery("#basic-informations").hide();
jQuery("#main-phpini").hide();
jQuery("#phple").hide();
jQuery("#wordpress").hide();
jQuery("#about").hide();
jQuery("#server-items").hide();
jQuery("#li-server").click(function(){
jQuery("#server-items").slideToggle(500);
jQuery("#wordpress").hide();
jQuery("#about").hide();
}); 
jQuery("#server-items-bi").click(function(){
jQuery("div#basic-informations").fadeToggle(300);
}); 
jQuery("#server-items-php").click(function(){
jQuery("div#phpinfo").fadeToggle(300);
}); 
jQuery("#server-items-phpini").click(function(){
jQuery("div#main-phpini").fadeToggle(300);
}); 
jQuery("#server-items-phple").click(function(){
jQuery("#phple").fadeToggle(300);
}); 
jQuery("#li-wordpress").click(function(){
jQuery("#wordpress").fadeToggle(300);
jQuery("#server-items").hide();
jQuery("#basic-informations").hide();
jQuery("#files").hide();
jQuery("#main-phpini").hide();
jQuery("#phple").hide();
jQuery("#about").hide();
}); 
jQuery("#li-about").click(function(){
jQuery("#about").fadeToggle(300);
jQuery("#wordpress").hide();
jQuery("#server-items").hide();
jQuery("#basic-informations").hide();
jQuery("#files").hide();
jQuery("#main-phpini").hide();
jQuery("#phple").hide();
}); 
});